// src/styles/HomeTabStyles.ts
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff', paddingHorizontal: 16 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 15,
  },
  avatar: { width: 52, height: 52, borderRadius: 26, marginRight: 12 },
  helloText: { fontSize: 14, color: '#777' },
  username: { fontSize: 20, fontWeight: '700', color: '#111' },
  notifBtn: {
    position: 'relative',
    padding: 8,
    borderRadius: 20,
    backgroundColor: '#f8f8f8',
  },
  notifDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: 'red',
    position: 'absolute',
    top: 5,
    right: 5,
  },
  locationName: {
    fontSize: 22,
    fontWeight: '600',
    color: '#2E7D32',
    textAlign: 'center',
    marginBottom: 8,
    marginTop: 20,
    letterSpacing: 0.5,
  },
  weatherCard: {
    backgroundColor: '#E8F5E9',
    borderRadius: 20,
    paddingVertical: 28,
    paddingHorizontal: 20,
    alignItems: 'center',
    marginBottom: 35,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    minHeight: 250,
    justifyContent: 'center',
  },
  viewDetailsText: {
    marginTop: 15,
    color: '#4CAF50',
    fontWeight: '600',
    fontSize: 14,
  },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    marginTop: 10,
    color: '#777',
  },
  errorContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorText: {
    marginTop: 10,
    color: '#777',
    textAlign: 'center',
    marginBottom: 15,
  },
  retryButton: {
    backgroundColor: '#4CAF50',
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 20,
  },
  retryText: {
    color: 'white',
    fontWeight: '600',
  },
  tempText: { fontSize: 44, fontWeight: '700', color: '#222', marginTop: 8 },
  weatherDesc: {
    fontSize: 16,
    fontWeight: '500',
    color: '#444',
    marginBottom: 20,
    textAlign: 'center',
  },
  weatherRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
    width: '100%',
  },
  weatherInfo: { alignItems: 'center', flex: 1 },
  weatherLabel: { fontSize: 16, fontWeight: '700', color: '#111' },
  weatherValue: { fontSize: 12, color: '#777' },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 14,
    marginTop: 10,
  },
  sectionTitle: { fontSize: 18, fontWeight: '700', color: '#222' },
  seeAll: { fontSize: 14, color: '#4CAF50' },
  fieldCard: {
    backgroundColor: 'white',
    borderRadius: 16,
    marginRight: 16,
    width: 160,
    padding: 10,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  fieldImage: {
    width: '100%',
    height: 95,
    borderRadius: 12,
    marginBottom: 8,
  },
  fieldStatusGood: {
    backgroundColor: '#C8E6C9',
    color: '#2E7D32',
    fontSize: 12,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    alignSelf: 'flex-start',
    marginBottom: 4,
  },
  fieldStatusBad: {
    backgroundColor: '#FFCDD2',
    color: '#C62828',
    fontSize: 12,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    alignSelf: 'flex-start',
    marginBottom: 4,
  },
  fieldName: { fontSize: 14, fontWeight: '600', marginTop: 4 },
  fieldArea: { fontSize: 12, color: '#777' },
  emptyCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    marginRight: 16,
    width: 160,
    paddingVertical: 20,
    paddingHorizontal: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#333',
    textAlign: 'center',
  },
  emptySubtitle: {
    fontSize: 12,
    color: '#666',
    marginTop: 6,
    textAlign: 'center',
  },
  taskCard: {
    backgroundColor: '#F5F5F5',
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    marginBottom: 20,
  },
  taskTitle: { fontSize: 15, fontWeight: '600', color: '#111' },
  taskSubtitle: { fontSize: 12, color: '#777' },
  taskTime: { fontSize: 13, fontWeight: '600', color: '#4CAF50' },

  // Notification popup styles
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  notificationPopup: {
    backgroundColor: 'white',
    borderRadius: 16,
    width: 320,
    maxHeight: 400,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
  },
  popupHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  popupTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#222',
  },
  notificationList: {
    maxHeight: 300,
  },
  notificationItem: {
    flexDirection: 'row',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  notifIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  notifContent: {
    flex: 1,
  },
  notifTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#222',
    marginBottom: 4,
  },
  notifMessage: {
    fontSize: 14,
    color: '#666',
    marginBottom: 4,
  },
  notifTime: {
    fontSize: 12,
    color: '#999',
  },

  // Weather Details Popup Styles
  modalBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  weatherDetailsPopup: {
    backgroundColor: 'white',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    width: '100%',
    height: '72%',
    position: 'absolute',
    bottom: 0,
    padding: 16,
    paddingBottom: 30,
  },
  weatherPopupHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f4f6f6',
  },
  grabber: {
    width: 48,
    height: 4,
    backgroundColor: '#e0e0e0',
    borderRadius: 4,
    alignSelf: 'center',
    marginBottom: 8,
  },
  weatherPopupTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#222',
  },
  weatherDetailsContent: {
    flex: 1,
    paddingTop: 6,
  },
  weatherSection: {
    marginBottom: 14,
    backgroundColor: '#fbfefe',
    borderRadius: 12,
    padding: 12,
  },
  currentWeatherHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  largeTemp: {
    fontSize: 28,
    fontWeight: '700',
    color: '#222',
    marginLeft: 15,
  },
  weatherCondition: {
    fontSize: 14,
    color: '#666',
    marginLeft: 15,
    marginTop: 4,
  },
  teaAdvice: {
    fontSize: 14,
    fontStyle: 'italic',
    color: '#4CAF50',
    textAlign: 'center',
    marginTop: 10,
    padding: 10,
    backgroundColor: '#E8F5E9',
    borderRadius: 10,
  },
  detailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e9ecef',
  },
  detailIconContainer: {
    width: 40,
    alignItems: 'center',
  },
  detailLabel: {
    flex: 1,
    fontSize: 14,
    color: '#666',
    marginLeft: 12,
  },
  detailValue: {
    fontSize: 16,
    fontWeight: '600',
    color: '#222',
  },

  // Forecast styles
  forecastScroll: {
    paddingVertical: 8,
  },
  forecastCard: {
    alignItems: 'center',
    marginHorizontal: 8,
    paddingVertical: 12,
    paddingHorizontal: 10,
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e9ecef',
    minWidth: 70,
  },
  forecastDay: {
    fontSize: 12,
    fontWeight: '600',
    color: '#222',
    marginBottom: 2,
  },
  forecastDate: {
    fontSize: 10,
    color: '#666',
    marginBottom: 8,
  },
  forecastIcon: {
    marginBottom: 8,
  },
  forecastHigh: {
    fontSize: 14,
    fontWeight: '700',
    color: '#222',
    marginBottom: 2,
  },
  forecastLow: {
    fontSize: 12,
    color: '#666',
    marginBottom: 4,
  },
  forecastRain: {
    fontSize: 10,
    color: '#2196F3',
    fontWeight: '600',
  },
});

export default styles;
